### PR TITLE
Add package: 2022_Fischer_Gauls

### LINKED ISSUE #1: Please add: 2022_Fischer_Gauls
## Check for existing package

I have checked the following places for the requested package and could not find
it:

- [x] Poseidon Minotaur Archive
- [x] The `packages/` directory in this repository
- [x] Open issues in this repository
- [x] Open pull requests in this repository

## Required information for the package

- DOI of publication: https://doi.org/10.1016/j.isci.2022.104094
- Project accession number:
  [PRJEB50940](https://www.ebi.ac.uk/ena/browser/view/PRJEB50940)

## Will you work on this?

Yes :)

### PR DESCRIPTION
**Pull request by scarlhoff**
Closes #1 

## PR Checklist

- [x] Add the appropriate label to your PR (`new package` or `package_update`).
- [x] The PR title is in the format `Add/update package: {package_name}`.
- [x] The PR description includes a link to the issue requesting the package its
      update.

If adding a package:

- [x] This PR contains a sequencingSourceFile (`.ssf`) for the requested
      package.
- [x] The name of the `.ssf` file(s) matches the package name (i.e.
      `packages/2023_my_package/2023_my_package.ssf`).
- [x] Comment `@delphis-bot create backbone` to this pull request to awaken
      Poseidon's trusty helper. (This should be repeated whenever changes are
      made to the SSF file contents).

Delphis-bot will then add a number of files to the PR. Check that they are all
there:

- [x] The file `packages/{package_name}/{package_name}.tsv` was added to the PR.
- [x] The file `packages/{package_name}/{package_name}.tsv_patch.sh` was added
      to the PR from template.
- [x] The file `packages/{package_name}/script_versions.txt` was added to the
      PR.
- [x] The file `packages/{package_name}/{package_name}.config` was added to the
    PR from template.

### Package SSF file (`*.ssf`)

- [x] I confirm that the `poseidon_IDs`, `udg`, and `library_built` are filled
      and correct.
- [x] I made sure to leave `notes` where necessary to explain any special
      cases/judgement calls made for data entries.

### Package TSV file (`*.tsv`)

- [x] I confirm that the `UDG`, `Strandedness` columns are correct for each
      library.
- [x] I confirm that the `R1_target_file` and `R2_target_file` columns point to
      the correct FastQ files for the library (i.e. consistent with SSF file).

### Package config file (`*.config`)

The template config file includes a few `TODO` statements, and information about
them. Please ensure that you:

- [x] I have selected the appropriate config for the CaptureType of the package.
- [x] If any nf-core/eager parameters need to be altered from their defaults, I
      have added them within the `params` section at the end of the package
      config file.

### CODE REVIEW

**Comment by scarlhoff** [comment]
@delphis-bot create backbone

**Comment by TCLamnidis** [comment]
@delphis-bot create recipe

**Comment by TCLamnidis** [comment]
@delphis-bot create recipe

**Comment by TCLamnidis** [comment]
@delphis-bot create recipe

**Review by stschiff — APPROVED** [review]
This looks good to me. Thank you @scarlhoff

**Comment by TCLamnidis** [comment]
This recipe is ready. I am currently bumping the nf-core/eager version used by minotaur, before merging the PR.

**Comment by stschiff** [comment]
Update?

**Comment by TCLamnidis** [comment]
Updating to use latest minotaur release

**Comment by TCLamnidis** [comment]
@delphis-bot create recipe

**Review by TCLamnidis — APPROVED** [review]

**Pull request merged**
